# Generated by Django 4.0.3 on 2023-11-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0007_answer_author_alter_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='pub_date',
            new_name='answer_date',
        ),
    ]
