# Generated by Django 4.0.3 on 2023-11-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0010_choice_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voter',
        ),
    ]
