# Generated by Django 4.0.3 on 2023-11-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0013_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
    ]
