# Generated by Django 4.0.3 on 2023-11-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='create_date',
            new_name='pub_date',
        ),
    ]
