# Generated by Django 4.0.3 on 2023-11-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_create_date_answer_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
