# Generated by Django 4.0.3 on 2023-11-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_question_voter_alter_answer_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
    ]
