# Generated by Django 4.0.3 on 2023-11-12 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0009_rename_pub_date_question_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='voter_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
